CITOYEN_CONTROLLER: AppDAF\CONTROLLER\CitoyenController
DATABASE: AppDAF\CORE\Database
CITOYEN_REPOSITORY: AppDAF\REPOSITORY\CitoyenRepository
LOG_REPOSITOTY: AppDAF\REPOSITORY\LogRepository
CITOYEN_SERVICE:  AppDAF\SERVICE\CitoyenService
LOG_SERVICE:  AppDAF\SERVICE\LogService
CLOUD_SERVICE:  AppDAF\SERVICE\CloudService